<?php

return [
    // The Telegram BOT api token
    'token' => env('TELEGRAM_TOKEN'),

    // if the webhook mode must validate the incoming IP range is from a telegram server
    'safe_mode' => env('APP_ENV', 'local') === 'production',

    // Extra or specific configurations
    'config' => [],

    // Set if the service provider should automatically load
    // handlers from /routes/telegram.php
    'routes' => true,

    // Enable or disable Nutgram mixins
    'mixins' => false,

    // Path to save files generated by nutgram:make command
    'namespace' => app_path('Telegram'),

    // Set log channel
    'log_channel' => env('TELEGRAM_LOG_CHANNEL', 'null'),

    // main channel id
    'telegram_channel_id' => env('TELEGRAM_CHANNEL_ID'),

    // main group id
    'telegram_group_id' => env('TELEGRAM_GROUP_ID'),
    
    // admins controlls group id
    'admin_controlls_group_id' => env('TELEGRAM_ADMINS_CONTROLLS_GROUP_ID'),
];
